name: 'ecommerce-project'

services:
  # PostgreSQL Veritabanı Servisi
  postgres:
    image: postgres:16-alpine
    container_name: ecom_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ecom_db
    ports:
      - "5433:5432" # Portu 5433 olarak değiştirdik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend API Servisi (Express.js)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ecom_backend_api
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/src/app/backend
      # node_modules'ü host makineden mount etme, konteyner içindekini kullan
      - /usr/src/app/backend/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5001
    depends_on:
      - postgres
    restart: unless-stopped
    command: pnpm dev

  # Frontend Web Uygulaması (Next.js)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ecom_frontend_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
      # node_modules'ü host makineden mount etme, konteyner içindekini kullan
      - /usr/src/app/frontend/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
      - INTERNAL_API_URL=http://backend:5001
    depends_on:
      - backend
    restart: unless-stopped
    command: pnpm dev

  # pgAdmin Servisi (Veritabanı Yönetim Arayüzü)
  pgadmin:
    image: dpage/pgadmin4
    container_name: ecom_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    name: ecom_postgres_data
